[package]
name = "katam-rando"
version = "0.1.0"
authors = ["Cuda Cheese <cudacheese@gmail.com>"]

[dependencies]
rand = "*"
bidir-map = "*"
csv = "1.0.0-beta.5"
serde_derive = "1.0.32"
serde = "1.0.32"
